services:
  certgen:
    build: ./docker/certgen
    container_name: certgen
    profiles: ["tools"]
    network_mode: "none"
    environment:
      - SRV_CN=broker
      - SRV_SAN=DNS:broker,DNS:localhost
      - CLIENT_CN_LIST=
    volumes:
      - ./certs:/work/certs
    working_dir: /work
