services:
  broker:
    image: eclipse-mosquitto:2
    container_name: broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./certs:/mosquitto/certs
      - broker_data:/mosquitto/data
      - broker_log:/mosquitto/log
    networks: [labnet]

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Warsaw
    networks: [labnet]
    depends_on:
      - broker
    volumes:
      - node_red_data:/data

  device_publisher:
    build:
      context: ./devices/publisher
    container_name: device_publisher
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MQTT_MODE_DEFAULT=${MQTT_MODE_DEFAULT:-PLAIN}
      - MQTT_CONTROL_TOPIC=${MQTT_CONTROL_TOPIC:-lab/control}
      - MQTT_PLAIN_HOST=${MQTT_PLAIN_HOST:-broker}
      - MQTT_PLAIN_PORT=${MQTT_PLAIN_PORT:-1883}
      - MQTT_TLS_HOST=${MQTT_TLS_HOST:-broker}
      - MQTT_TLS_PORT=${MQTT_TLS_PORT:-8883}
      - MQTT_TLS_CA=${MQTT_TLS_CA:-/certs/ca.crt}
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - DEVICE_NAME=${PUB_DEVICE_NAME:-publisher-1}
      - HEARTBEAT_SEC=${PUB_HEARTBEAT_SEC:-1.0}
      - MQTT_TOPIC_PUB=${MQTT_TOPIC_PUB:-}
      - MQTT_QOS=${MQTT_QOS:-0}
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
    networks: [labnet]
    depends_on:
      - broker

  device_subscriber:
    build:
      context: ./devices/subscriber
    container_name: device_subscriber
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MQTT_MODE_DEFAULT=${MQTT_MODE_DEFAULT:-PLAIN}
      - MQTT_CONTROL_TOPIC=${MQTT_CONTROL_TOPIC:-lab/control}
      - MQTT_PLAIN_HOST=${MQTT_PLAIN_HOST:-broker}
      - MQTT_PLAIN_PORT=${MQTT_PLAIN_PORT:-1883}
      - MQTT_TLS_HOST=${MQTT_TLS_HOST:-broker}
      - MQTT_TLS_PORT=${MQTT_TLS_PORT:-8883}
      - MQTT_TLS_CA=${MQTT_TLS_CA:-/certs/ca.crt}
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - DEVICE_NAME=${SUB_DEVICE_NAME:-subscriber-1}
      - HEARTBEAT_SEC=${SUB_HEARTBEAT_SEC:-1.0}
      - MQTT_TOPIC_SUB=${MQTT_TOPIC_SUB:-lab/telemetry/#}
      - MQTT_TOPIC_METRICS=${MQTT_TOPIC_METRICS:-lab/metrics}
      - MQTT_QOS=${MQTT_QOS:-0}
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
    networks: [labnet]
    depends_on:
      - broker

  sniffer:
    image: nicolaka/netshoot:latest
    container_name: sniffer
    network_mode: "service:broker"
    cap_add: ["NET_ADMIN", "NET_RAW"]
    restart: unless-stopped
    command: ["sleep", "infinity"]
    volumes:
      - ./pcap:/pcap
    depends_on:
      - broker

networks:
  labnet:
    driver: bridge

volumes:
  broker_data:
  broker_log:
  node_red_data:
